version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-fire
    depends_on:
            - api
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    restart: always
    networks:
      - api-network
  api:
    image: flask:0.0.1
    container_name: api-python
    build: 
      context: ./
      dockerfile: build/app/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=/app/app.py
    command: flask run --host=0.0.0.0
    restart: always
    networks:
      api-network:
        aliases:
          - flask-app

networks:
  api-network: