version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-fire
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
    restart: always
    networks:
      main:
        aliases:
          - nginx

# volumes:
#   nginx.conf:

networks:
  main: