version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-fire
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
    restart: always
    networks:
      main:
        aliases:
          - nginx
  api:
    container_name: api-python
    build: 
      context: ./
      dockerfile: build/app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    networks:
      main:
        aliases:
          - api
# volumes:
#   nginx.conf:

networks:
  main: